import { fileURLToPath } from 'node:url';
import mdx from '@astrojs/mdx';
import { satteri } from '@astrojs/markdown-satteri';
import sitemap from '@astrojs/sitemap';
import expressiveCode from 'astro-expressive-code';
import { defineConfig, fontProviders } from 'astro/config';
import { sitemapHooks } from './src/lib/sitemap';
import { blogHastPlugins } from './src/plugins';

const publicDir = fileURLToPath(new URL('./public', import.meta.url));
const postsDir = fileURLToPath(new URL('./src/content/posts', import.meta.url));
const sitemapOptions = sitemapHooks(postsDir, 'https://bugs.cc');

// https://astro.build/config
export default defineConfig({
  site: 'https://bugs.cc',
  output: 'static',
  trailingSlash: 'always',
  // Inline every stylesheet: the whole site CSS is ~3 KB gzipped and a
  // render-blocking request costs a full round trip on slow mobile (LCP).
  build: { format: 'directory', inlineStylesheets: 'always' },
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'zh'],
    routing: { prefixDefaultLocale: false },
  },
  integrations: [
    // Expressive Code must come before mdx(); with Sätteri it registers its own
    // HAST plugin (appended after the plugins listed in markdown.processor).
    expressiveCode(),
    mdx(),
    sitemap({
      // Allowlist of real pages (home, lists, posts, tag pages) computed from
      // the content: alias redirect pages (including the old Chinese post
      // URLs under /zh/posts/), `/en/` and 404 stay out. See src/lib/sitemap.ts.
      filter: sitemapOptions.filter,
      // `xhtml:link` alternates (en / zh / x-default, paired by translationKey
      // like the HTML hreflang) and per-URL `lastmod`; see src/lib/sitemap.ts.
      // The integration's own `i18n` option is not used: it pairs by identical
      // path and emits `en-US` / `zh-CN`, which would disagree with the HTML.
      serialize: sitemapOptions.serialize,
    }),
  ],
  markdown: {
    processor: satteri({
      hastPlugins: blogHastPlugins(publicDir),
    }),
  },
  fonts: [
    {
      provider: fontProviders.local(),
      name: 'Fira Code',
      cssVariable: '--font-mono',
      display: 'swap',
      fallbacks: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      options: {
        variants: [
          {
            // Latin subset of Fira Code VF pinned at weight 400 (29 KB instead
            // of 113 KB), generated by `bun run font` (scripts/subset-font.ts).
            weight: '400',
            style: 'normal',
            src: ['./src/assets/fonts/FiraCode-latin-400.woff2'],
          },
        ],
      },
    },
  ],
});
